repos:
  - repo: local
    hooks: # Hooks are the tools that will be run on your code
      - id: pylint # Run the pylint before commit
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
            "--load-plugins=pylint.extensions.docparams", # Load an extension
        ]
        pass_filenames: true

      - id: check-commit-msg
        name: check commit msg
        entry: |
         bash -c '
            MSG=$(cat "$0")
            if [[ "$MSG" =~ ^(feat|fix|docs|style|refactor|perf|test|chore|build|ci)(\([a-z-]+\))?:\ .+ ]]; then
              echo "✅ Valid commit message!"
              exit 0
            else
              echo "❌ Invalid format!"
              echo "📝 Use: <type>(<scope>): <description>"
              echo "💡 Example: feat(auth): add social login"
              exit 1
            fi
          '
        language: system
        pass_filenames: true
        stages: [commit-msg]