[project]
name = "default-template-ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pylint>=3.3.8",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
